// <auto-generated />
using System;
using ExchangeRateDB.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ExchangeRateDB.Migrations
{
    [DbContext(typeof(ExchangeRateDbContext))]
    [Migration("20230817124820_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ExchangeRateDB.Model.Currency", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Symbol")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Currencies");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "United Arab Emirates Dirham",
                            Symbol = "AED"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Afghan Afghani",
                            Symbol = "AFN"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Albanian Lek",
                            Symbol = "ALL"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Armenian Dram",
                            Symbol = "AMD"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Netherlands Antillean Guilder",
                            Symbol = "ANG"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Angolan Kwanza",
                            Symbol = "AOA"
                        },
                        new
                        {
                            Id = 7,
                            Name = "Argentine Peso",
                            Symbol = "ARS"
                        },
                        new
                        {
                            Id = 8,
                            Name = "Australian Dollar",
                            Symbol = "AUD"
                        },
                        new
                        {
                            Id = 9,
                            Name = "Aruban Florin",
                            Symbol = "AWG"
                        },
                        new
                        {
                            Id = 10,
                            Name = "Azerbaijani Manat",
                            Symbol = "AZN"
                        },
                        new
                        {
                            Id = 11,
                            Name = "Bosnian Convertible Mark",
                            Symbol = "BAM"
                        },
                        new
                        {
                            Id = 12,
                            Name = "Barbadian or Bajan Dollar",
                            Symbol = "BBD"
                        },
                        new
                        {
                            Id = 13,
                            Name = "Bangladeshi Taka",
                            Symbol = "BDT"
                        },
                        new
                        {
                            Id = 14,
                            Name = "Bulgarian Lev",
                            Symbol = "BGN"
                        },
                        new
                        {
                            Id = 15,
                            Name = "Bahraini Dinar",
                            Symbol = "BHD"
                        },
                        new
                        {
                            Id = 16,
                            Name = "Burundian Franc",
                            Symbol = "BIF"
                        },
                        new
                        {
                            Id = 17,
                            Name = "Bermudian Dollar",
                            Symbol = "BMD"
                        },
                        new
                        {
                            Id = 18,
                            Name = "Bruneian Dollar",
                            Symbol = "BND"
                        },
                        new
                        {
                            Id = 19,
                            Name = "Bolivian Bolíviano",
                            Symbol = "BOB"
                        },
                        new
                        {
                            Id = 20,
                            Name = "Brazilian Real",
                            Symbol = "BRL"
                        },
                        new
                        {
                            Id = 21,
                            Name = "Bahamian Dollar",
                            Symbol = "BSD"
                        },
                        new
                        {
                            Id = 22,
                            Name = "Bhutanese Ngultrum",
                            Symbol = "BTN"
                        },
                        new
                        {
                            Id = 23,
                            Name = "Botswana Pula",
                            Symbol = "BWP"
                        },
                        new
                        {
                            Id = 24,
                            Name = "Belarusian Ruble",
                            Symbol = "BYN"
                        },
                        new
                        {
                            Id = 25,
                            Name = "Belizean Dollar",
                            Symbol = "BZD"
                        },
                        new
                        {
                            Id = 26,
                            Name = "Canadian Dollar",
                            Symbol = "CAD"
                        },
                        new
                        {
                            Id = 27,
                            Name = "Congolese Franc",
                            Symbol = "CDF"
                        },
                        new
                        {
                            Id = 28,
                            Name = "Swiss Franc",
                            Symbol = "CHF"
                        },
                        new
                        {
                            Id = 29,
                            Name = "Chilean Peso",
                            Symbol = "CLP"
                        },
                        new
                        {
                            Id = 30,
                            Name = "Chinese Yuan Renminbi",
                            Symbol = "CNY"
                        },
                        new
                        {
                            Id = 31,
                            Name = "Colombian Peso",
                            Symbol = "COP"
                        },
                        new
                        {
                            Id = 32,
                            Name = "Costa Rican Colon",
                            Symbol = "CRC"
                        },
                        new
                        {
                            Id = 33,
                            Name = "Cuban Convertible Peso",
                            Symbol = "CUC"
                        },
                        new
                        {
                            Id = 34,
                            Name = "Cuban Peso",
                            Symbol = "CUP"
                        },
                        new
                        {
                            Id = 35,
                            Name = "Cape Verdean Escudo",
                            Symbol = "CVE"
                        },
                        new
                        {
                            Id = 36,
                            Name = "Czech Koruna",
                            Symbol = "CZK"
                        },
                        new
                        {
                            Id = 37,
                            Name = "Djiboutian Franc",
                            Symbol = "DJF"
                        },
                        new
                        {
                            Id = 38,
                            Name = "Danish Krone",
                            Symbol = "DKK"
                        },
                        new
                        {
                            Id = 39,
                            Name = "Dominican Peso",
                            Symbol = "DOP"
                        },
                        new
                        {
                            Id = 40,
                            Name = "Algerian Dinar",
                            Symbol = "DZD"
                        },
                        new
                        {
                            Id = 41,
                            Name = "Egyptian Pound",
                            Symbol = "EGP"
                        },
                        new
                        {
                            Id = 42,
                            Name = "Eritrean Nakfa",
                            Symbol = "ERN"
                        },
                        new
                        {
                            Id = 43,
                            Name = "Ethiopian Birr",
                            Symbol = "ETB"
                        },
                        new
                        {
                            Id = 44,
                            Name = "Euro",
                            Symbol = "EUR"
                        },
                        new
                        {
                            Id = 45,
                            Name = "Fijian Dollar",
                            Symbol = "FJD"
                        },
                        new
                        {
                            Id = 46,
                            Name = "Falkland Island Pound",
                            Symbol = "FKP"
                        },
                        new
                        {
                            Id = 47,
                            Name = "British Pound Sterling",
                            Symbol = "GBP"
                        },
                        new
                        {
                            Id = 48,
                            Name = "Georgian Lari",
                            Symbol = "GEL"
                        },
                        new
                        {
                            Id = 49,
                            Name = "Guernsey Pound",
                            Symbol = "GGP"
                        },
                        new
                        {
                            Id = 50,
                            Name = "Ghanaian Cedi",
                            Symbol = "GHS"
                        },
                        new
                        {
                            Id = 51,
                            Name = "Gibraltar Pound",
                            Symbol = "GIP"
                        },
                        new
                        {
                            Id = 52,
                            Name = "Gambian Dalasi",
                            Symbol = "GMD"
                        },
                        new
                        {
                            Id = 53,
                            Name = "Guinean Franc",
                            Symbol = "GNF"
                        },
                        new
                        {
                            Id = 54,
                            Name = "Guatemalan Quetzal",
                            Symbol = "GTQ"
                        },
                        new
                        {
                            Id = 55,
                            Name = "Guyanese Dollar",
                            Symbol = "GYD"
                        },
                        new
                        {
                            Id = 56,
                            Name = "Hong Kong Dollar",
                            Symbol = "HKD"
                        },
                        new
                        {
                            Id = 57,
                            Name = "Honduran Lempira",
                            Symbol = "HNL"
                        },
                        new
                        {
                            Id = 58,
                            Name = "Croatian Kuna",
                            Symbol = "HRK"
                        },
                        new
                        {
                            Id = 59,
                            Name = "Haitian Gourde",
                            Symbol = "HTG"
                        },
                        new
                        {
                            Id = 60,
                            Name = "Hungarian Forint",
                            Symbol = "HUF"
                        },
                        new
                        {
                            Id = 61,
                            Name = "Indonesian Rupiah",
                            Symbol = "IDR"
                        },
                        new
                        {
                            Id = 62,
                            Name = "Israeli Shekel",
                            Symbol = "ILS"
                        },
                        new
                        {
                            Id = 63,
                            Name = "Isle of Man Pound",
                            Symbol = "IMP"
                        },
                        new
                        {
                            Id = 64,
                            Name = "Indian Rupee",
                            Symbol = "INR"
                        },
                        new
                        {
                            Id = 65,
                            Name = "Iraqi Dinar",
                            Symbol = "IQD"
                        },
                        new
                        {
                            Id = 66,
                            Name = "Iranian Rial",
                            Symbol = "IRR"
                        },
                        new
                        {
                            Id = 67,
                            Name = "Icelandic Krona",
                            Symbol = "ISK"
                        },
                        new
                        {
                            Id = 68,
                            Name = "Jersey Pound",
                            Symbol = "JEP"
                        },
                        new
                        {
                            Id = 69,
                            Name = "Jamaican Dollar",
                            Symbol = "JMD"
                        },
                        new
                        {
                            Id = 70,
                            Name = "Jordanian Dinar",
                            Symbol = "JOD"
                        },
                        new
                        {
                            Id = 71,
                            Name = "Japanese Yen",
                            Symbol = "JPY"
                        },
                        new
                        {
                            Id = 72,
                            Name = "Kenyan Shilling",
                            Symbol = "KES"
                        },
                        new
                        {
                            Id = 73,
                            Name = "Kyrgyzstani Som",
                            Symbol = "KGS"
                        },
                        new
                        {
                            Id = 74,
                            Name = "Cambodian Riel",
                            Symbol = "KHR"
                        },
                        new
                        {
                            Id = 75,
                            Name = "Comorian Franc",
                            Symbol = "KMF"
                        },
                        new
                        {
                            Id = 76,
                            Name = "North Korean Won",
                            Symbol = "KPW"
                        },
                        new
                        {
                            Id = 77,
                            Name = "South Korean Won",
                            Symbol = "KRW"
                        },
                        new
                        {
                            Id = 78,
                            Name = "Kuwaiti Dinar",
                            Symbol = "KWD"
                        },
                        new
                        {
                            Id = 79,
                            Name = "Caymanian Dollar",
                            Symbol = "KYD"
                        },
                        new
                        {
                            Id = 80,
                            Name = "Kazakhstani Tenge",
                            Symbol = "KZT"
                        },
                        new
                        {
                            Id = 81,
                            Name = "Lao Kip",
                            Symbol = "LAK"
                        },
                        new
                        {
                            Id = 82,
                            Name = "Lebanese Pound",
                            Symbol = "LBP"
                        },
                        new
                        {
                            Id = 83,
                            Name = "Sri Lankan Rupee",
                            Symbol = "LKR"
                        },
                        new
                        {
                            Id = 84,
                            Name = "Liberian Dollar",
                            Symbol = "LRD"
                        },
                        new
                        {
                            Id = 85,
                            Name = "Basotho Loti",
                            Symbol = "LSL"
                        },
                        new
                        {
                            Id = 86,
                            Name = "Libyan Dinar",
                            Symbol = "LYD"
                        },
                        new
                        {
                            Id = 87,
                            Name = "Moroccan Dirham",
                            Symbol = "MAD"
                        },
                        new
                        {
                            Id = 88,
                            Name = "Moldovan Leu",
                            Symbol = "MDL"
                        },
                        new
                        {
                            Id = 89,
                            Name = "Malagasy Ariary",
                            Symbol = "MGA"
                        },
                        new
                        {
                            Id = 90,
                            Name = "Macedonian Denar",
                            Symbol = "MKD"
                        },
                        new
                        {
                            Id = 91,
                            Name = "Burmese Kyat",
                            Symbol = "MMK"
                        },
                        new
                        {
                            Id = 92,
                            Name = "Mongolian Tughrik",
                            Symbol = "MNT"
                        },
                        new
                        {
                            Id = 93,
                            Name = "Macau Pataca",
                            Symbol = "MOP"
                        },
                        new
                        {
                            Id = 94,
                            Name = "Mauritanian Ouguiya",
                            Symbol = "MRO"
                        },
                        new
                        {
                            Id = 95,
                            Name = "Mauritanian Ouguiya",
                            Symbol = "MRU"
                        },
                        new
                        {
                            Id = 96,
                            Name = "Mauritian Rupee",
                            Symbol = "MUR"
                        },
                        new
                        {
                            Id = 97,
                            Name = "Maldivian Rufiyaa",
                            Symbol = "MVR"
                        },
                        new
                        {
                            Id = 98,
                            Name = "Malawian Kwacha",
                            Symbol = "MWK"
                        },
                        new
                        {
                            Id = 99,
                            Name = "Mexican Peso",
                            Symbol = "MXN"
                        },
                        new
                        {
                            Id = 100,
                            Name = "Malaysian Ringgit",
                            Symbol = "MYR"
                        },
                        new
                        {
                            Id = 101,
                            Name = "Mozambican Metical",
                            Symbol = "MZN"
                        },
                        new
                        {
                            Id = 102,
                            Name = "Namibian Dollar",
                            Symbol = "NAD"
                        },
                        new
                        {
                            Id = 103,
                            Name = "Nigerian Naira",
                            Symbol = "NGN"
                        },
                        new
                        {
                            Id = 104,
                            Name = "Nicaraguan Cordoba",
                            Symbol = "NIO"
                        },
                        new
                        {
                            Id = 105,
                            Name = "Norwegian Krone",
                            Symbol = "NOK"
                        },
                        new
                        {
                            Id = 106,
                            Name = "Nepalese Rupee",
                            Symbol = "NPR"
                        },
                        new
                        {
                            Id = 107,
                            Name = "New Zealand Dollar",
                            Symbol = "NZD"
                        },
                        new
                        {
                            Id = 108,
                            Name = "Omani Rial",
                            Symbol = "OMR"
                        },
                        new
                        {
                            Id = 109,
                            Name = "Panamanian Balboa",
                            Symbol = "PAB"
                        },
                        new
                        {
                            Id = 110,
                            Name = "Peruvian Sol",
                            Symbol = "PEN"
                        },
                        new
                        {
                            Id = 111,
                            Name = "Papua New Guinean Kina",
                            Symbol = "PGK"
                        },
                        new
                        {
                            Id = 112,
                            Name = "Philippine Peso",
                            Symbol = "PHP"
                        },
                        new
                        {
                            Id = 113,
                            Name = "Pakistani Rupee",
                            Symbol = "PKR"
                        },
                        new
                        {
                            Id = 114,
                            Name = "Polish Złoty",
                            Symbol = "PLN"
                        },
                        new
                        {
                            Id = 115,
                            Name = "Paraguayan Guarani",
                            Symbol = "PYG"
                        },
                        new
                        {
                            Id = 116,
                            Name = "Qatari Riyal",
                            Symbol = "QAR"
                        },
                        new
                        {
                            Id = 117,
                            Name = "Romanian Leu",
                            Symbol = "RON"
                        },
                        new
                        {
                            Id = 118,
                            Name = "Serbian Dinar",
                            Symbol = "RSD"
                        },
                        new
                        {
                            Id = 119,
                            Name = "Russian Ruble",
                            Symbol = "RUB"
                        },
                        new
                        {
                            Id = 120,
                            Name = "Rwandan Franc",
                            Symbol = "RWF"
                        },
                        new
                        {
                            Id = 121,
                            Name = "Saudi Arabian Riyal",
                            Symbol = "SAR"
                        },
                        new
                        {
                            Id = 122,
                            Name = "Solomon Islander Dollar",
                            Symbol = "SBD"
                        },
                        new
                        {
                            Id = 123,
                            Name = "Seychellois Rupee",
                            Symbol = "SCR"
                        },
                        new
                        {
                            Id = 124,
                            Name = "Sudanese Pound",
                            Symbol = "SDG"
                        },
                        new
                        {
                            Id = 125,
                            Name = "Swedish Krona",
                            Symbol = "SEK"
                        },
                        new
                        {
                            Id = 126,
                            Name = "Singapore Dollar",
                            Symbol = "SGD"
                        },
                        new
                        {
                            Id = 127,
                            Name = "Saint Helenian Pound",
                            Symbol = "SHP"
                        },
                        new
                        {
                            Id = 128,
                            Name = "Sierra Leonean Leone",
                            Symbol = "SLL"
                        },
                        new
                        {
                            Id = 129,
                            Name = "Somali Shilling",
                            Symbol = "SOS"
                        },
                        new
                        {
                            Id = 130,
                            Name = "Seborgan Luigino",
                            Symbol = "SPL"
                        },
                        new
                        {
                            Id = 131,
                            Name = "Surinamese Dollar",
                            Symbol = "SRD"
                        },
                        new
                        {
                            Id = 132,
                            Name = "Sao Tomean Dobra",
                            Symbol = "STN"
                        },
                        new
                        {
                            Id = 133,
                            Name = "Salvadoran Colon",
                            Symbol = "SVC"
                        },
                        new
                        {
                            Id = 134,
                            Name = "Syrian Pound",
                            Symbol = "SYP"
                        },
                        new
                        {
                            Id = 135,
                            Name = "Swazi Lilangeni",
                            Symbol = "SZL"
                        },
                        new
                        {
                            Id = 136,
                            Name = "Thai Baht",
                            Symbol = "THB"
                        },
                        new
                        {
                            Id = 137,
                            Name = "Tajikistani Somoni",
                            Symbol = "TJS"
                        },
                        new
                        {
                            Id = 138,
                            Name = "Turkmenistani Manat",
                            Symbol = "TMT"
                        },
                        new
                        {
                            Id = 139,
                            Name = "Tunisian Dinar",
                            Symbol = "TND"
                        },
                        new
                        {
                            Id = 140,
                            Name = "Tongan Pa'anga",
                            Symbol = "TOP"
                        },
                        new
                        {
                            Id = 141,
                            Name = "Turkish Lira",
                            Symbol = "TRY"
                        },
                        new
                        {
                            Id = 142,
                            Name = "Trinidadian Dollar",
                            Symbol = "TTD"
                        },
                        new
                        {
                            Id = 143,
                            Name = "Tuvaluan Dollar",
                            Symbol = "TVD"
                        },
                        new
                        {
                            Id = 144,
                            Name = "Taiwan New Dollar",
                            Symbol = "TWD"
                        },
                        new
                        {
                            Id = 145,
                            Name = "Tanzanian Shilling",
                            Symbol = "TZS"
                        },
                        new
                        {
                            Id = 146,
                            Name = "Ukrainian Hryvnia",
                            Symbol = "UAH"
                        },
                        new
                        {
                            Id = 147,
                            Name = "Ugandan Shilling",
                            Symbol = "UGX"
                        },
                        new
                        {
                            Id = 148,
                            Name = "US Dollar",
                            Symbol = "USD"
                        },
                        new
                        {
                            Id = 149,
                            Name = "Uruguayan Peso",
                            Symbol = "UYU"
                        },
                        new
                        {
                            Id = 150,
                            Name = "Uzbekistani Som",
                            Symbol = "UZS"
                        },
                        new
                        {
                            Id = 151,
                            Name = "Venezuelan Bolívar",
                            Symbol = "VEF"
                        },
                        new
                        {
                            Id = 152,
                            Name = "Venezuelan Bolívar Soberano",
                            Symbol = "VES"
                        },
                        new
                        {
                            Id = 153,
                            Name = "Vietnamese Dong",
                            Symbol = "VND"
                        },
                        new
                        {
                            Id = 154,
                            Name = "Ni-Vanuatu Vatu",
                            Symbol = "VUV"
                        },
                        new
                        {
                            Id = 155,
                            Name = "Samoan Tala",
                            Symbol = "WST"
                        },
                        new
                        {
                            Id = 156,
                            Name = "Central African CFA Franc BEAC",
                            Symbol = "XAF"
                        },
                        new
                        {
                            Id = 157,
                            Name = "East Caribbean Dollar",
                            Symbol = "XCD"
                        },
                        new
                        {
                            Id = 158,
                            Name = "Special Drawing Rights",
                            Symbol = "XDR"
                        },
                        new
                        {
                            Id = 159,
                            Name = "West African CFA franc",
                            Symbol = "XOF"
                        },
                        new
                        {
                            Id = 160,
                            Name = "CFP Franc",
                            Symbol = "XPF"
                        },
                        new
                        {
                            Id = 161,
                            Name = "Yemeni Rial",
                            Symbol = "YER"
                        },
                        new
                        {
                            Id = 162,
                            Name = "South African Rand",
                            Symbol = "ZAR"
                        },
                        new
                        {
                            Id = 163,
                            Name = "Zambian Kwacha",
                            Symbol = "ZMW"
                        },
                        new
                        {
                            Id = 164,
                            Name = "Zimbabwean Dollar",
                            Symbol = "ZWL"
                        });
                });

            modelBuilder.Entity("ExchangeRateDB.Model.Rate", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CurrencyId")
                        .HasColumnType("int");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("Value")
                        .HasColumnType("decimal(20, 10)");

                    b.HasKey("Id");

                    b.HasIndex("CurrencyId", "Date")
                        .IsUnique();

                    b.ToTable("Rates");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CurrencyId = 1,
                            Date = new DateTime(2023, 8, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Value = 4.026409m
                        },
                        new
                        {
                            Id = 2,
                            CurrencyId = 2,
                            Date = new DateTime(2023, 8, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Value = 92.482921m
                        },
                        new
                        {
                            Id = 3,
                            CurrencyId = 3,
                            Date = new DateTime(2023, 8, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Value = 103.792055m
                        },
                        new
                        {
                            Id = 4,
                            CurrencyId = 4,
                            Date = new DateTime(2023, 8, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Value = 426.367363m
                        },
                        new
                        {
                            Id = 5,
                            CurrencyId = 5,
                            Date = new DateTime(2023, 8, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Value = 1.981148m
                        },
                        new
                        {
                            Id = 6,
                            CurrencyId = 6,
                            Date = new DateTime(2023, 8, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Value = 904.502417m
                        },
                        new
                        {
                            Id = 7,
                            CurrencyId = 7,
                            Date = new DateTime(2023, 8, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Value = 314.514925m
                        },
                        new
                        {
                            Id = 8,
                            CurrencyId = 8,
                            Date = new DateTime(2023, 8, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Value = 1.686486m
                        },
                        new
                        {
                            Id = 9,
                            CurrencyId = 9,
                            Date = new DateTime(2023, 8, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Value = 1.9762m
                        },
                        new
                        {
                            Id = 10,
                            CurrencyId = 10,
                            Date = new DateTime(2023, 8, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Value = 1.868175m
                        },
                        new
                        {
                            Id = 11,
                            CurrencyId = 11,
                            Date = new DateTime(2023, 8, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Value = 1.95565m
                        },
                        new
                        {
                            Id = 12,
                            CurrencyId = 12,
                            Date = new DateTime(2023, 8, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Value = 2.21953m
                        },
                        new
                        {
                            Id = 13,
                            CurrencyId = 13,
                            Date = new DateTime(2023, 8, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Value = 120.32079m
                        },
                        new
                        {
                            Id = 14,
                            CurrencyId = 14,
                            Date = new DateTime(2023, 8, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Value = 1.958954m
                        },
                        new
                        {
                            Id = 15,
                            CurrencyId = 15,
                            Date = new DateTime(2023, 8, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Value = 0.414368m
                        },
                        new
                        {
                            Id = 16,
                            CurrencyId = 16,
                            Date = new DateTime(2023, 8, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Value = 3115.461523m
                        },
                        new
                        {
                            Id = 17,
                            CurrencyId = 17,
                            Date = new DateTime(2023, 8, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Value = 1.096366m
                        },
                        new
                        {
                            Id = 18,
                            CurrencyId = 18,
                            Date = new DateTime(2023, 8, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Value = 1.484086m
                        },
                        new
                        {
                            Id = 19,
                            CurrencyId = 19,
                            Date = new DateTime(2023, 8, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Value = 7.596419m
                        },
                        new
                        {
                            Id = 20,
                            CurrencyId = 20,
                            Date = new DateTime(2023, 8, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Value = 5.380648m
                        },
                        new
                        {
                            Id = 21,
                            CurrencyId = 21,
                            Date = new DateTime(2023, 8, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Value = 1.099216m
                        },
                        new
                        {
                            Id = 22,
                            CurrencyId = 22,
                            Date = new DateTime(2023, 8, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Value = 91.079128m
                        },
                        new
                        {
                            Id = 23,
                            CurrencyId = 23,
                            Date = new DateTime(2023, 8, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Value = 14.834864m
                        },
                        new
                        {
                            Id = 24,
                            CurrencyId = 24,
                            Date = new DateTime(2023, 8, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Value = 2.774688m
                        },
                        new
                        {
                            Id = 25,
                            CurrencyId = 25,
                            Date = new DateTime(2023, 8, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Value = 2.21583m
                        },
                        new
                        {
                            Id = 26,
                            CurrencyId = 26,
                            Date = new DateTime(2023, 8, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Value = 1.473462m
                        },
                        new
                        {
                            Id = 27,
                            CurrencyId = 27,
                            Date = new DateTime(2023, 8, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Value = 2675.133625m
                        },
                        new
                        {
                            Id = 28,
                            CurrencyId = 28,
                            Date = new DateTime(2023, 8, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Value = 0.961372m
                        },
                        new
                        {
                            Id = 29,
                            CurrencyId = 29,
                            Date = new DateTime(2023, 8, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Value = 930.518772m
                        },
                        new
                        {
                            Id = 30,
                            CurrencyId = 30,
                            Date = new DateTime(2023, 8, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Value = 7.933967m
                        },
                        new
                        {
                            Id = 31,
                            CurrencyId = 31,
                            Date = new DateTime(2023, 8, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Value = 4343.267539m
                        },
                        new
                        {
                            Id = 32,
                            CurrencyId = 32,
                            Date = new DateTime(2023, 8, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Value = 588.254971m
                        },
                        new
                        {
                            Id = 33,
                            CurrencyId = 33,
                            Date = new DateTime(2023, 8, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Value = 1.096366m
                        },
                        new
                        {
                            Id = 34,
                            CurrencyId = 34,
                            Date = new DateTime(2023, 8, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Value = 29.053701m
                        },
                        new
                        {
                            Id = 35,
                            CurrencyId = 35,
                            Date = new DateTime(2023, 8, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Value = 110.25656m
                        },
                        new
                        {
                            Id = 36,
                            CurrencyId = 36,
                            Date = new DateTime(2023, 8, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Value = 24.094513m
                        },
                        new
                        {
                            Id = 37,
                            CurrencyId = 37,
                            Date = new DateTime(2023, 8, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Value = 195.725018m
                        },
                        new
                        {
                            Id = 38,
                            CurrencyId = 38,
                            Date = new DateTime(2023, 8, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Value = 7.461653m
                        },
                        new
                        {
                            Id = 39,
                            CurrencyId = 39,
                            Date = new DateTime(2023, 8, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Value = 62.385225m
                        },
                        new
                        {
                            Id = 40,
                            CurrencyId = 40,
                            Date = new DateTime(2023, 8, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Value = 149.040435m
                        },
                        new
                        {
                            Id = 41,
                            CurrencyId = 41,
                            Date = new DateTime(2023, 8, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Value = 33.82941m
                        },
                        new
                        {
                            Id = 42,
                            CurrencyId = 42,
                            Date = new DateTime(2023, 8, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Value = 16.445491m
                        },
                        new
                        {
                            Id = 43,
                            CurrencyId = 43,
                            Date = new DateTime(2023, 8, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Value = 60.626259m
                        },
                        new
                        {
                            Id = 44,
                            CurrencyId = 44,
                            Date = new DateTime(2023, 8, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Value = 0m
                        },
                        new
                        {
                            Id = 45,
                            CurrencyId = 45,
                            Date = new DateTime(2023, 8, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Value = 2.461566m
                        },
                        new
                        {
                            Id = 46,
                            CurrencyId = 46,
                            Date = new DateTime(2023, 8, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Value = 0.86379m
                        },
                        new
                        {
                            Id = 47,
                            CurrencyId = 47,
                            Date = new DateTime(2023, 8, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Value = 0.863688m
                        },
                        new
                        {
                            Id = 48,
                            CurrencyId = 48,
                            Date = new DateTime(2023, 8, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Value = 2.856078m
                        },
                        new
                        {
                            Id = 49,
                            CurrencyId = 49,
                            Date = new DateTime(2023, 8, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Value = 0.86379m
                        },
                        new
                        {
                            Id = 50,
                            CurrencyId = 50,
                            Date = new DateTime(2023, 8, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Value = 12.28406m
                        },
                        new
                        {
                            Id = 51,
                            CurrencyId = 51,
                            Date = new DateTime(2023, 8, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Value = 0.86379m
                        },
                        new
                        {
                            Id = 52,
                            CurrencyId = 52,
                            Date = new DateTime(2023, 8, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Value = 66.224736m
                        },
                        new
                        {
                            Id = 53,
                            CurrencyId = 53,
                            Date = new DateTime(2023, 8, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Value = 9448.276769m
                        },
                        new
                        {
                            Id = 54,
                            CurrencyId = 54,
                            Date = new DateTime(2023, 8, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Value = 8.646338m
                        },
                        new
                        {
                            Id = 55,
                            CurrencyId = 55,
                            Date = new DateTime(2023, 8, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Value = 229.982396m
                        },
                        new
                        {
                            Id = 56,
                            CurrencyId = 56,
                            Date = new DateTime(2023, 8, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Value = 8.571007m
                        },
                        new
                        {
                            Id = 57,
                            CurrencyId = 57,
                            Date = new DateTime(2023, 8, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Value = 27.03993m
                        },
                        new
                        {
                            Id = 58,
                            CurrencyId = 58,
                            Date = new DateTime(2023, 8, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Value = 7.371811m
                        },
                        new
                        {
                            Id = 59,
                            CurrencyId = 59,
                            Date = new DateTime(2023, 8, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Value = 150.048514m
                        },
                        new
                        {
                            Id = 60,
                            CurrencyId = 60,
                            Date = new DateTime(2023, 8, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Value = 383.750479m
                        },
                        new
                        {
                            Id = 61,
                            CurrencyId = 61,
                            Date = new DateTime(2023, 8, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Value = 16800.220403m
                        },
                        new
                        {
                            Id = 62,
                            CurrencyId = 62,
                            Date = new DateTime(2023, 8, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Value = 4.086709m
                        },
                        new
                        {
                            Id = 63,
                            CurrencyId = 63,
                            Date = new DateTime(2023, 8, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Value = 0.86379m
                        },
                        new
                        {
                            Id = 64,
                            CurrencyId = 64,
                            Date = new DateTime(2023, 8, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Value = 90.950857m
                        },
                        new
                        {
                            Id = 65,
                            CurrencyId = 65,
                            Date = new DateTime(2023, 8, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Value = 1439.789789m
                        },
                        new
                        {
                            Id = 66,
                            CurrencyId = 66,
                            Date = new DateTime(2023, 8, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Value = 46389.993829m
                        },
                        new
                        {
                            Id = 67,
                            CurrencyId = 67,
                            Date = new DateTime(2023, 8, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Value = 144.943779m
                        },
                        new
                        {
                            Id = 68,
                            CurrencyId = 68,
                            Date = new DateTime(2023, 8, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Value = 0.86379m
                        },
                        new
                        {
                            Id = 69,
                            CurrencyId = 69,
                            Date = new DateTime(2023, 8, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Value = 169.946991m
                        },
                        new
                        {
                            Id = 70,
                            CurrencyId = 70,
                            Date = new DateTime(2023, 8, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Value = 0.776012m
                        },
                        new
                        {
                            Id = 71,
                            CurrencyId = 71,
                            Date = new DateTime(2023, 8, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Value = 158.86897m
                        },
                        new
                        {
                            Id = 72,
                            CurrencyId = 72,
                            Date = new DateTime(2023, 8, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Value = 156.318034m
                        },
                        new
                        {
                            Id = 73,
                            CurrencyId = 73,
                            Date = new DateTime(2023, 8, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Value = 96.502564m
                        },
                        new
                        {
                            Id = 74,
                            CurrencyId = 74,
                            Date = new DateTime(2023, 8, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Value = 4544.652124m
                        },
                        new
                        {
                            Id = 75,
                            CurrencyId = 75,
                            Date = new DateTime(2023, 8, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Value = 493.172914m
                        },
                        new
                        {
                            Id = 76,
                            CurrencyId = 76,
                            Date = new DateTime(2023, 8, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Value = 986.707632m
                        },
                        new
                        {
                            Id = 77,
                            CurrencyId = 77,
                            Date = new DateTime(2023, 8, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Value = 1458.828859m
                        },
                        new
                        {
                            Id = 78,
                            CurrencyId = 78,
                            Date = new DateTime(2023, 8, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Value = 0.337265m
                        },
                        new
                        {
                            Id = 79,
                            CurrencyId = 79,
                            Date = new DateTime(2023, 8, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Value = 0.91603m
                        },
                        new
                        {
                            Id = 80,
                            CurrencyId = 80,
                            Date = new DateTime(2023, 8, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Value = 491.022414m
                        },
                        new
                        {
                            Id = 81,
                            CurrencyId = 81,
                            Date = new DateTime(2023, 8, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Value = 21367.364407m
                        },
                        new
                        {
                            Id = 82,
                            CurrencyId = 82,
                            Date = new DateTime(2023, 8, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Value = 16500.736929m
                        },
                        new
                        {
                            Id = 83,
                            CurrencyId = 83,
                            Date = new DateTime(2023, 8, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Value = 352.882988m
                        },
                        new
                        {
                            Id = 84,
                            CurrencyId = 84,
                            Date = new DateTime(2023, 8, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Value = 204.695685m
                        },
                        new
                        {
                            Id = 85,
                            CurrencyId = 85,
                            Date = new DateTime(2023, 8, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Value = 20.506181m
                        },
                        new
                        {
                            Id = 86,
                            CurrencyId = 86,
                            Date = new DateTime(2023, 8, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Value = 5.271596m
                        },
                        new
                        {
                            Id = 87,
                            CurrencyId = 87,
                            Date = new DateTime(2023, 8, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Value = 10.742178m
                        },
                        new
                        {
                            Id = 88,
                            CurrencyId = 88,
                            Date = new DateTime(2023, 8, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Value = 19.374517m
                        },
                        new
                        {
                            Id = 89,
                            CurrencyId = 89,
                            Date = new DateTime(2023, 8, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Value = 4954.620742m
                        },
                        new
                        {
                            Id = 90,
                            CurrencyId = 90,
                            Date = new DateTime(2023, 8, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Value = 61.615284m
                        },
                        new
                        {
                            Id = 91,
                            CurrencyId = 91,
                            Date = new DateTime(2023, 8, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Value = 2308.423299m
                        },
                        new
                        {
                            Id = 92,
                            CurrencyId = 92,
                            Date = new DateTime(2023, 8, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Value = 3790.742518m
                        },
                        new
                        {
                            Id = 93,
                            CurrencyId = 93,
                            Date = new DateTime(2023, 8, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Value = 8.850323m
                        },
                        new
                        {
                            Id = 94,
                            CurrencyId = 94,
                            Date = new DateTime(2023, 8, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Value = 391.402501m
                        },
                        new
                        {
                            Id = 95,
                            CurrencyId = 96,
                            Date = new DateTime(2023, 8, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Value = 49.559851m
                        },
                        new
                        {
                            Id = 96,
                            CurrencyId = 97,
                            Date = new DateTime(2023, 8, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Value = 16.829634m
                        },
                        new
                        {
                            Id = 97,
                            CurrencyId = 98,
                            Date = new DateTime(2023, 8, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Value = 1193.00868m
                        },
                        new
                        {
                            Id = 98,
                            CurrencyId = 99,
                            Date = new DateTime(2023, 8, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Value = 18.652371m
                        },
                        new
                        {
                            Id = 99,
                            CurrencyId = 100,
                            Date = new DateTime(2023, 8, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Value = 5.029074m
                        },
                        new
                        {
                            Id = 100,
                            CurrencyId = 101,
                            Date = new DateTime(2023, 8, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Value = 69.345568m
                        },
                        new
                        {
                            Id = 101,
                            CurrencyId = 102,
                            Date = new DateTime(2023, 8, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Value = 20.506134m
                        },
                        new
                        {
                            Id = 102,
                            CurrencyId = 103,
                            Date = new DateTime(2023, 8, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Value = 843.328873m
                        },
                        new
                        {
                            Id = 103,
                            CurrencyId = 104,
                            Date = new DateTime(2023, 8, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Value = 40.216922m
                        },
                        new
                        {
                            Id = 104,
                            CurrencyId = 105,
                            Date = new DateTime(2023, 8, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Value = 11.432252m
                        },
                        new
                        {
                            Id = 105,
                            CurrencyId = 106,
                            Date = new DateTime(2023, 8, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Value = 145.726845m
                        },
                        new
                        {
                            Id = 106,
                            CurrencyId = 107,
                            Date = new DateTime(2023, 8, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Value = 1.831857m
                        },
                        new
                        {
                            Id = 107,
                            CurrencyId = 108,
                            Date = new DateTime(2023, 8, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Value = 0.422143m
                        },
                        new
                        {
                            Id = 108,
                            CurrencyId = 109,
                            Date = new DateTime(2023, 8, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Value = 1.099316m
                        },
                        new
                        {
                            Id = 109,
                            CurrencyId = 110,
                            Date = new DateTime(2023, 8, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Value = 4.031691m
                        },
                        new
                        {
                            Id = 110,
                            CurrencyId = 111,
                            Date = new DateTime(2023, 8, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Value = 3.994694m
                        },
                        new
                        {
                            Id = 111,
                            CurrencyId = 112,
                            Date = new DateTime(2023, 8, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Value = 61.991283m
                        },
                        new
                        {
                            Id = 112,
                            CurrencyId = 113,
                            Date = new DateTime(2023, 8, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Value = 317.028233m
                        },
                        new
                        {
                            Id = 113,
                            CurrencyId = 114,
                            Date = new DateTime(2023, 8, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Value = 4.441012m
                        },
                        new
                        {
                            Id = 114,
                            CurrencyId = 115,
                            Date = new DateTime(2023, 8, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Value = 7987.388595m
                        },
                        new
                        {
                            Id = 115,
                            CurrencyId = 116,
                            Date = new DateTime(2023, 8, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Value = 3.991911m
                        },
                        new
                        {
                            Id = 116,
                            CurrencyId = 117,
                            Date = new DateTime(2023, 8, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Value = 4.946846m
                        },
                        new
                        {
                            Id = 117,
                            CurrencyId = 118,
                            Date = new DateTime(2023, 8, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Value = 117.261024m
                        },
                        new
                        {
                            Id = 118,
                            CurrencyId = 119,
                            Date = new DateTime(2023, 8, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Value = 109.631168m
                        },
                        new
                        {
                            Id = 119,
                            CurrencyId = 120,
                            Date = new DateTime(2023, 8, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Value = 1297.000719m
                        },
                        new
                        {
                            Id = 120,
                            CurrencyId = 121,
                            Date = new DateTime(2023, 8, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Value = 4.113526m
                        },
                        new
                        {
                            Id = 121,
                            CurrencyId = 122,
                            Date = new DateTime(2023, 8, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Value = 9.175254m
                        },
                        new
                        {
                            Id = 122,
                            CurrencyId = 123,
                            Date = new DateTime(2023, 8, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Value = 14.610216m
                        },
                        new
                        {
                            Id = 123,
                            CurrencyId = 124,
                            Date = new DateTime(2023, 8, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Value = 659.347746m
                        },
                        new
                        {
                            Id = 124,
                            CurrencyId = 125,
                            Date = new DateTime(2023, 8, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Value = 11.850663m
                        },
                        new
                        {
                            Id = 125,
                            CurrencyId = 126,
                            Date = new DateTime(2023, 8, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Value = 1.482401m
                        },
                        new
                        {
                            Id = 126,
                            CurrencyId = 127,
                            Date = new DateTime(2023, 8, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Value = 1.334004m
                        },
                        new
                        {
                            Id = 127,
                            CurrencyId = 128,
                            Date = new DateTime(2023, 8, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Value = 21653.230396m
                        },
                        new
                        {
                            Id = 128,
                            CurrencyId = 129,
                            Date = new DateTime(2023, 8, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Value = 624.384499m
                        },
                        new
                        {
                            Id = 129,
                            CurrencyId = 131,
                            Date = new DateTime(2023, 8, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Value = 41.908635m
                        },
                        new
                        {
                            Id = 130,
                            CurrencyId = 134,
                            Date = new DateTime(2023, 8, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Value = 14362.126262m
                        },
                        new
                        {
                            Id = 131,
                            CurrencyId = 135,
                            Date = new DateTime(2023, 8, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Value = 20.703415m
                        },
                        new
                        {
                            Id = 132,
                            CurrencyId = 136,
                            Date = new DateTime(2023, 8, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Value = 38.449963m
                        },
                        new
                        {
                            Id = 133,
                            CurrencyId = 137,
                            Date = new DateTime(2023, 8, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Value = 12.053477m
                        },
                        new
                        {
                            Id = 134,
                            CurrencyId = 138,
                            Date = new DateTime(2023, 8, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Value = 3.837281m
                        },
                        new
                        {
                            Id = 135,
                            CurrencyId = 139,
                            Date = new DateTime(2023, 8, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Value = 3.386401m
                        },
                        new
                        {
                            Id = 136,
                            CurrencyId = 140,
                            Date = new DateTime(2023, 8, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Value = 2.600964m
                        },
                        new
                        {
                            Id = 137,
                            CurrencyId = 141,
                            Date = new DateTime(2023, 8, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Value = 29.687515m
                        },
                        new
                        {
                            Id = 138,
                            CurrencyId = 142,
                            Date = new DateTime(2023, 8, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Value = 7.461429m
                        },
                        new
                        {
                            Id = 139,
                            CurrencyId = 144,
                            Date = new DateTime(2023, 8, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Value = 34.983401m
                        },
                        new
                        {
                            Id = 140,
                            CurrencyId = 145,
                            Date = new DateTime(2023, 8, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Value = 2753.689215m
                        },
                        new
                        {
                            Id = 141,
                            CurrencyId = 146,
                            Date = new DateTime(2023, 8, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Value = 40.597492m
                        },
                        new
                        {
                            Id = 142,
                            CurrencyId = 147,
                            Date = new DateTime(2023, 8, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Value = 4100.686108m
                        },
                        new
                        {
                            Id = 143,
                            CurrencyId = 148,
                            Date = new DateTime(2023, 8, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Value = 1.096366m
                        },
                        new
                        {
                            Id = 144,
                            CurrencyId = 149,
                            Date = new DateTime(2023, 8, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Value = 41.736805m
                        },
                        new
                        {
                            Id = 145,
                            CurrencyId = 150,
                            Date = new DateTime(2023, 8, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Value = 13273.983925m
                        },
                        new
                        {
                            Id = 146,
                            CurrencyId = 151,
                            Date = new DateTime(2023, 8, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Value = 3433270.83167m
                        },
                        new
                        {
                            Id = 147,
                            CurrencyId = 152,
                            Date = new DateTime(2023, 8, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Value = 32.963995m
                        },
                        new
                        {
                            Id = 148,
                            CurrencyId = 153,
                            Date = new DateTime(2023, 8, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Value = 26049.657995m
                        },
                        new
                        {
                            Id = 149,
                            CurrencyId = 154,
                            Date = new DateTime(2023, 8, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Value = 132.252171m
                        },
                        new
                        {
                            Id = 150,
                            CurrencyId = 155,
                            Date = new DateTime(2023, 8, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Value = 3.026002m
                        },
                        new
                        {
                            Id = 151,
                            CurrencyId = 156,
                            Date = new DateTime(2023, 8, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Value = 655.906793m
                        },
                        new
                        {
                            Id = 152,
                            CurrencyId = 157,
                            Date = new DateTime(2023, 8, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Value = 2.962985m
                        },
                        new
                        {
                            Id = 153,
                            CurrencyId = 158,
                            Date = new DateTime(2023, 8, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Value = 0.822237m
                        },
                        new
                        {
                            Id = 154,
                            CurrencyId = 159,
                            Date = new DateTime(2023, 8, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Value = 655.906793m
                        },
                        new
                        {
                            Id = 155,
                            CurrencyId = 160,
                            Date = new DateTime(2023, 8, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Value = 119.668756m
                        },
                        new
                        {
                            Id = 156,
                            CurrencyId = 161,
                            Date = new DateTime(2023, 8, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Value = 274.475646m
                        },
                        new
                        {
                            Id = 157,
                            CurrencyId = 162,
                            Date = new DateTime(2023, 8, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Value = 20.7789m
                        },
                        new
                        {
                            Id = 158,
                            CurrencyId = 163,
                            Date = new DateTime(2023, 8, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Value = 20.963395m
                        },
                        new
                        {
                            Id = 159,
                            CurrencyId = 164,
                            Date = new DateTime(2023, 8, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Value = 353.02943m
                        });
                });

            modelBuilder.Entity("ExchangeRateDB.Model.UpdateLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("ApiCallSuccess")
                        .HasColumnType("bit");

                    b.Property<DateTime>("DbUpdateDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("UpdateLogs");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ApiCallSuccess = false,
                            DbUpdateDate = new DateTime(2023, 8, 17, 14, 48, 20, 226, DateTimeKind.Local).AddTicks(6377),
                            Message = "DB Created"
                        });
                });

            modelBuilder.Entity("ExchangeRateDB.Model.Rate", b =>
                {
                    b.HasOne("ExchangeRateDB.Model.Currency", "Currency")
                        .WithMany("Rates")
                        .HasForeignKey("CurrencyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Currency");
                });

            modelBuilder.Entity("ExchangeRateDB.Model.Currency", b =>
                {
                    b.Navigation("Rates");
                });
#pragma warning restore 612, 618
        }
    }
}
