// <auto-generated />
using ExchangeRateDB.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ExchangeRateDB.Migrations
{
    [DbContext(typeof(ExchangeRateDbContext))]
    partial class ExchangeRateDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ExchangeRateAPI.Model.Currency", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Symbol")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Currencies");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Euro",
                            Symbol = "EUR"
                        },
                        new
                        {
                            Id = 2,
                            Name = "United Arab Emirates Dirham",
                            Symbol = "AED"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Afghan Afghani",
                            Symbol = "AFN"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Albanian Lek",
                            Symbol = "ALL"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Armenian Dram",
                            Symbol = "AMD"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Netherlands Antillean Guilder",
                            Symbol = "ANG"
                        },
                        new
                        {
                            Id = 7,
                            Name = "Angolan Kwanza",
                            Symbol = "AOA"
                        },
                        new
                        {
                            Id = 8,
                            Name = "Argentine Peso",
                            Symbol = "ARS"
                        },
                        new
                        {
                            Id = 9,
                            Name = "Australian Dollar",
                            Symbol = "AUD"
                        },
                        new
                        {
                            Id = 10,
                            Name = "Aruban Florin",
                            Symbol = "AWG"
                        },
                        new
                        {
                            Id = 11,
                            Name = "Azerbaijani Manat",
                            Symbol = "AZN"
                        },
                        new
                        {
                            Id = 12,
                            Name = "Bosnia-Herzegovina Convertible Mark",
                            Symbol = "BAM"
                        },
                        new
                        {
                            Id = 13,
                            Name = "Barbadian Dollar",
                            Symbol = "BBD"
                        },
                        new
                        {
                            Id = 14,
                            Name = "Bangladeshi Taka",
                            Symbol = "BDT"
                        },
                        new
                        {
                            Id = 15,
                            Name = "Bulgarian Lev",
                            Symbol = "BGN"
                        },
                        new
                        {
                            Id = 16,
                            Name = "Bahraini Dinar",
                            Symbol = "BHD"
                        },
                        new
                        {
                            Id = 17,
                            Name = "Burundian Franc",
                            Symbol = "BIF"
                        },
                        new
                        {
                            Id = 18,
                            Name = "Bermudian Dollar",
                            Symbol = "BMD"
                        },
                        new
                        {
                            Id = 19,
                            Name = "Brunei Dollar",
                            Symbol = "BND"
                        },
                        new
                        {
                            Id = 20,
                            Name = "Bolivian Bolíviano",
                            Symbol = "BOB"
                        },
                        new
                        {
                            Id = 21,
                            Name = "Brazilian Real",
                            Symbol = "BRL"
                        },
                        new
                        {
                            Id = 22,
                            Name = "Bahamian Dollar",
                            Symbol = "BSD"
                        },
                        new
                        {
                            Id = 23,
                            Name = "Bitcoin",
                            Symbol = "BTC"
                        },
                        new
                        {
                            Id = 24,
                            Name = "Bhutanese Ngultrum",
                            Symbol = "BTN"
                        },
                        new
                        {
                            Id = 25,
                            Name = "Botswana Pula",
                            Symbol = "BWP"
                        },
                        new
                        {
                            Id = 26,
                            Name = "Belarusian Ruble",
                            Symbol = "BYN"
                        },
                        new
                        {
                            Id = 27,
                            Name = "Belarusian Ruble (till 2016)",
                            Symbol = "BYR"
                        },
                        new
                        {
                            Id = 28,
                            Name = "Belize Dollar",
                            Symbol = "BZD"
                        },
                        new
                        {
                            Id = 29,
                            Name = "Canadian Dollar",
                            Symbol = "CAD"
                        },
                        new
                        {
                            Id = 30,
                            Name = "Congolese Franc",
                            Symbol = "CDF"
                        },
                        new
                        {
                            Id = 31,
                            Name = "Swiss Franc",
                            Symbol = "CHF"
                        },
                        new
                        {
                            Id = 32,
                            Name = "Chilean Unit of Account (UF)",
                            Symbol = "CLF"
                        },
                        new
                        {
                            Id = 33,
                            Name = "Chilean Peso",
                            Symbol = "CLP"
                        },
                        new
                        {
                            Id = 34,
                            Name = "Chinese Yuan",
                            Symbol = "CNY"
                        },
                        new
                        {
                            Id = 35,
                            Name = "Colombian Peso",
                            Symbol = "COP"
                        },
                        new
                        {
                            Id = 36,
                            Name = "Costa Rican Colón",
                            Symbol = "CRC"
                        },
                        new
                        {
                            Id = 37,
                            Name = "Cuban Convertible Peso",
                            Symbol = "CUC"
                        },
                        new
                        {
                            Id = 38,
                            Name = "Cuban Peso",
                            Symbol = "CUP"
                        },
                        new
                        {
                            Id = 39,
                            Name = "Cape Verdean Escudo",
                            Symbol = "CVE"
                        },
                        new
                        {
                            Id = 40,
                            Name = "Czech Republic Koruna",
                            Symbol = "CZK"
                        },
                        new
                        {
                            Id = 41,
                            Name = "Djiboutian Franc",
                            Symbol = "DJF"
                        },
                        new
                        {
                            Id = 42,
                            Name = "Danish Krone",
                            Symbol = "DKK"
                        },
                        new
                        {
                            Id = 43,
                            Name = "Dominican Peso",
                            Symbol = "DOP"
                        },
                        new
                        {
                            Id = 44,
                            Name = "Algerian Dinar",
                            Symbol = "DZD"
                        },
                        new
                        {
                            Id = 45,
                            Name = "Egyptian Pound",
                            Symbol = "EGP"
                        },
                        new
                        {
                            Id = 46,
                            Name = "Eritrean Nakfa",
                            Symbol = "ERN"
                        },
                        new
                        {
                            Id = 47,
                            Name = "Ethiopian Birr",
                            Symbol = "ETB"
                        },
                        new
                        {
                            Id = 48,
                            Name = "Fijian Dollar",
                            Symbol = "FJD"
                        },
                        new
                        {
                            Id = 49,
                            Name = "Falkland Islands Pound",
                            Symbol = "FKP"
                        },
                        new
                        {
                            Id = 50,
                            Name = "British Pound Sterling",
                            Symbol = "GBP"
                        },
                        new
                        {
                            Id = 51,
                            Name = "Georgian Lari",
                            Symbol = "GEL"
                        },
                        new
                        {
                            Id = 52,
                            Name = "Guernsey Pound",
                            Symbol = "GGP"
                        },
                        new
                        {
                            Id = 53,
                            Name = "Ghanaian Cedi",
                            Symbol = "GHS"
                        },
                        new
                        {
                            Id = 54,
                            Name = "Gibraltar Pound",
                            Symbol = "GIP"
                        },
                        new
                        {
                            Id = 55,
                            Name = "Gambian Dalasi",
                            Symbol = "GMD"
                        },
                        new
                        {
                            Id = 56,
                            Name = "Guinean Franc",
                            Symbol = "GNF"
                        },
                        new
                        {
                            Id = 57,
                            Name = "Guatemalan Quetzal",
                            Symbol = "GTQ"
                        },
                        new
                        {
                            Id = 58,
                            Name = "Guyanese Dollar",
                            Symbol = "GYD"
                        },
                        new
                        {
                            Id = 59,
                            Name = "Hong Kong Dollar",
                            Symbol = "HKD"
                        },
                        new
                        {
                            Id = 60,
                            Name = "Honduran Lempira",
                            Symbol = "HNL"
                        },
                        new
                        {
                            Id = 61,
                            Name = "Croatian Kuna",
                            Symbol = "HRK"
                        },
                        new
                        {
                            Id = 62,
                            Name = "Haitian Gourde",
                            Symbol = "HTG"
                        },
                        new
                        {
                            Id = 63,
                            Name = "Hungarian Forint",
                            Symbol = "HUF"
                        },
                        new
                        {
                            Id = 64,
                            Name = "Indonesian Rupiah",
                            Symbol = "IDR"
                        },
                        new
                        {
                            Id = 65,
                            Name = "Israeli New Sheqel",
                            Symbol = "ILS"
                        },
                        new
                        {
                            Id = 66,
                            Name = "Manx pound",
                            Symbol = "IMP"
                        },
                        new
                        {
                            Id = 67,
                            Name = "Indian Rupee",
                            Symbol = "INR"
                        },
                        new
                        {
                            Id = 68,
                            Name = "Iraqi Dinar",
                            Symbol = "IQD"
                        },
                        new
                        {
                            Id = 69,
                            Name = "Iranian Rial",
                            Symbol = "IRR"
                        },
                        new
                        {
                            Id = 70,
                            Name = "Icelandic Króna",
                            Symbol = "ISK"
                        },
                        new
                        {
                            Id = 71,
                            Name = "Jersey Pound",
                            Symbol = "JEP"
                        },
                        new
                        {
                            Id = 72,
                            Name = "Jamaican Dollar",
                            Symbol = "JMD"
                        },
                        new
                        {
                            Id = 73,
                            Name = "Jordanian Dinar",
                            Symbol = "JOD"
                        },
                        new
                        {
                            Id = 74,
                            Name = "Japanese Yen",
                            Symbol = "JPY"
                        },
                        new
                        {
                            Id = 75,
                            Name = "Kenyan Shilling",
                            Symbol = "KES"
                        },
                        new
                        {
                            Id = 76,
                            Name = "Kyrgyzstani Som",
                            Symbol = "KGS"
                        },
                        new
                        {
                            Id = 77,
                            Name = "Cambodian Riel",
                            Symbol = "KHR"
                        },
                        new
                        {
                            Id = 78,
                            Name = "Comorian Franc",
                            Symbol = "KMF"
                        },
                        new
                        {
                            Id = 79,
                            Name = "North Korean Won",
                            Symbol = "KPW"
                        },
                        new
                        {
                            Id = 80,
                            Name = "South Korean Won",
                            Symbol = "KRW"
                        },
                        new
                        {
                            Id = 81,
                            Name = "Kuwaiti Dinar",
                            Symbol = "KWD"
                        },
                        new
                        {
                            Id = 82,
                            Name = "Cayman Islands Dollar",
                            Symbol = "KYD"
                        },
                        new
                        {
                            Id = 83,
                            Name = "Kazakhstani Tenge",
                            Symbol = "KZT"
                        },
                        new
                        {
                            Id = 84,
                            Name = "Laotian Kip",
                            Symbol = "LAK"
                        },
                        new
                        {
                            Id = 85,
                            Name = "Lebanese Pound",
                            Symbol = "LBP"
                        },
                        new
                        {
                            Id = 86,
                            Name = "Sri Lankan Rupee",
                            Symbol = "LKR"
                        },
                        new
                        {
                            Id = 87,
                            Name = "Liberian Dollar",
                            Symbol = "LRD"
                        },
                        new
                        {
                            Id = 88,
                            Name = "Lesotho Loti",
                            Symbol = "LSL"
                        },
                        new
                        {
                            Id = 89,
                            Name = "Lithuanian Litas",
                            Symbol = "LTL"
                        },
                        new
                        {
                            Id = 90,
                            Name = "Latvian Lats",
                            Symbol = "LVL"
                        },
                        new
                        {
                            Id = 91,
                            Name = "Libyan Dinar",
                            Symbol = "LYD"
                        },
                        new
                        {
                            Id = 92,
                            Name = "Moroccan Dirham",
                            Symbol = "MAD"
                        },
                        new
                        {
                            Id = 93,
                            Name = "Moldovan Leu",
                            Symbol = "MDL"
                        },
                        new
                        {
                            Id = 94,
                            Name = "Malagasy Ariary",
                            Symbol = "MGA"
                        },
                        new
                        {
                            Id = 95,
                            Name = "Macedonian Denar",
                            Symbol = "MKD"
                        },
                        new
                        {
                            Id = 96,
                            Name = "Myanma Kyat",
                            Symbol = "MMK"
                        },
                        new
                        {
                            Id = 97,
                            Name = "Mongolian Tugrik",
                            Symbol = "MNT"
                        },
                        new
                        {
                            Id = 98,
                            Name = "Macanese Pataca",
                            Symbol = "MOP"
                        },
                        new
                        {
                            Id = 99,
                            Name = "Mauritanian Ouguiya (till 2017)",
                            Symbol = "MRO"
                        },
                        new
                        {
                            Id = 100,
                            Name = "Mauritian Rupee",
                            Symbol = "MUR"
                        },
                        new
                        {
                            Id = 101,
                            Name = "Maldivian Rufiyaa",
                            Symbol = "MVR"
                        },
                        new
                        {
                            Id = 102,
                            Name = "Malawian Kwacha",
                            Symbol = "MWK"
                        },
                        new
                        {
                            Id = 103,
                            Name = "Mexican Peso",
                            Symbol = "MXN"
                        },
                        new
                        {
                            Id = 104,
                            Name = "Malaysian Ringgit",
                            Symbol = "MYR"
                        },
                        new
                        {
                            Id = 105,
                            Name = "Mozambican Metical",
                            Symbol = "MZN"
                        },
                        new
                        {
                            Id = 106,
                            Name = "Namibian Dollar",
                            Symbol = "NAD"
                        },
                        new
                        {
                            Id = 107,
                            Name = "Nigerian Naira",
                            Symbol = "NGN"
                        },
                        new
                        {
                            Id = 108,
                            Name = "Nicaraguan Córdoba",
                            Symbol = "NIO"
                        },
                        new
                        {
                            Id = 109,
                            Name = "Norwegian Krone",
                            Symbol = "NOK"
                        },
                        new
                        {
                            Id = 110,
                            Name = "Nepalese Rupee",
                            Symbol = "NPR"
                        },
                        new
                        {
                            Id = 111,
                            Name = "New Zealand Dollar",
                            Symbol = "NZD"
                        },
                        new
                        {
                            Id = 112,
                            Name = "Omani Rial",
                            Symbol = "OMR"
                        },
                        new
                        {
                            Id = 113,
                            Name = "Panamanian Balboa",
                            Symbol = "PAB"
                        },
                        new
                        {
                            Id = 114,
                            Name = "Peruvian Nuevo Sol",
                            Symbol = "PEN"
                        },
                        new
                        {
                            Id = 115,
                            Name = "Papua New Guinean Kina",
                            Symbol = "PGK"
                        },
                        new
                        {
                            Id = 116,
                            Name = "Philippine Peso",
                            Symbol = "PHP"
                        },
                        new
                        {
                            Id = 117,
                            Name = "Pakistani Rupee",
                            Symbol = "PKR"
                        },
                        new
                        {
                            Id = 118,
                            Name = "Polish Zloty",
                            Symbol = "PLN"
                        },
                        new
                        {
                            Id = 119,
                            Name = "Paraguayan Guarani",
                            Symbol = "PYG"
                        },
                        new
                        {
                            Id = 120,
                            Name = "Qatari Rial",
                            Symbol = "QAR"
                        },
                        new
                        {
                            Id = 121,
                            Name = "Romanian Leu",
                            Symbol = "RON"
                        },
                        new
                        {
                            Id = 122,
                            Name = "Serbian Dinar",
                            Symbol = "RSD"
                        },
                        new
                        {
                            Id = 123,
                            Name = "Russian Ruble",
                            Symbol = "RUB"
                        },
                        new
                        {
                            Id = 124,
                            Name = "Rwandan Franc",
                            Symbol = "RWF"
                        },
                        new
                        {
                            Id = 125,
                            Name = "Saudi Riyal",
                            Symbol = "SAR"
                        },
                        new
                        {
                            Id = 126,
                            Name = "Solomon Islands Dollar",
                            Symbol = "SBD"
                        },
                        new
                        {
                            Id = 127,
                            Name = "Seychellois Rupee",
                            Symbol = "SCR"
                        },
                        new
                        {
                            Id = 128,
                            Name = "Sudanese Pound",
                            Symbol = "SDG"
                        },
                        new
                        {
                            Id = 129,
                            Name = "Swedish Krona",
                            Symbol = "SEK"
                        },
                        new
                        {
                            Id = 130,
                            Name = "Singapore Dollar",
                            Symbol = "SGD"
                        },
                        new
                        {
                            Id = 131,
                            Name = "Saint Helena Pound",
                            Symbol = "SHP"
                        },
                        new
                        {
                            Id = 132,
                            Name = "Sierra Leonean Leone",
                            Symbol = "SLL"
                        },
                        new
                        {
                            Id = 133,
                            Name = "Somali Shilling",
                            Symbol = "SOS"
                        },
                        new
                        {
                            Id = 134,
                            Name = "Surinamese Dollar",
                            Symbol = "SRD"
                        },
                        new
                        {
                            Id = 135,
                            Name = "South Sudanese Pound",
                            Symbol = "SSP"
                        },
                        new
                        {
                            Id = 136,
                            Name = "São Tomé and Príncipe Dobra (pre-2018)",
                            Symbol = "STD"
                        },
                        new
                        {
                            Id = 137,
                            Name = "Salvadoran Colón",
                            Symbol = "SVC"
                        },
                        new
                        {
                            Id = 138,
                            Name = "Syrian Pound",
                            Symbol = "SYP"
                        },
                        new
                        {
                            Id = 139,
                            Name = "Swazi Lilangeni",
                            Symbol = "SZL"
                        },
                        new
                        {
                            Id = 140,
                            Name = "Thai Baht",
                            Symbol = "THB"
                        },
                        new
                        {
                            Id = 141,
                            Name = "Tajikistani Somoni",
                            Symbol = "TJS"
                        },
                        new
                        {
                            Id = 142,
                            Name = "Turkmenistani Manat",
                            Symbol = "TMT"
                        },
                        new
                        {
                            Id = 143,
                            Name = "Tunisian Dinar",
                            Symbol = "TND"
                        },
                        new
                        {
                            Id = 144,
                            Name = "Tongan Pa'anga",
                            Symbol = "TOP"
                        },
                        new
                        {
                            Id = 145,
                            Name = "Turkish Lira",
                            Symbol = "TRY"
                        },
                        new
                        {
                            Id = 146,
                            Name = "Trinidad and Tobago Dollar",
                            Symbol = "TTD"
                        },
                        new
                        {
                            Id = 147,
                            Name = "New Taiwan Dollar",
                            Symbol = "TWD"
                        },
                        new
                        {
                            Id = 148,
                            Name = "Tanzanian Shilling",
                            Symbol = "TZS"
                        },
                        new
                        {
                            Id = 149,
                            Name = "Ukrainian Hryvnia",
                            Symbol = "UAH"
                        },
                        new
                        {
                            Id = 150,
                            Name = "Ugandan Shilling",
                            Symbol = "UGX"
                        },
                        new
                        {
                            Id = 151,
                            Name = "United States Dollar",
                            Symbol = "USD"
                        },
                        new
                        {
                            Id = 152,
                            Name = "Uruguayan Peso",
                            Symbol = "UYU"
                        },
                        new
                        {
                            Id = 153,
                            Name = "Uzbekistan Som",
                            Symbol = "UZS"
                        },
                        new
                        {
                            Id = 154,
                            Name = "Venezuelan Bolívar Fuerte (Old)",
                            Symbol = "VEF"
                        },
                        new
                        {
                            Id = 155,
                            Name = "Vietnamese Dong",
                            Symbol = "VND"
                        },
                        new
                        {
                            Id = 156,
                            Name = "Vanuatu Vatu",
                            Symbol = "VUV"
                        },
                        new
                        {
                            Id = 157,
                            Name = "Samoan Tala",
                            Symbol = "WST"
                        });
                });

            modelBuilder.Entity("ExchangeRateAPI.Model.Rate", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CurrencyId")
                        .HasColumnType("int");

                    b.Property<string>("Date")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Value")
                        .HasColumnType("decimal(20, 10)");

                    b.HasKey("Id");

                    b.HasIndex("CurrencyId");

                    b.ToTable("Rates");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CurrencyId = 6,
                            Date = "1999-03-03",
                            Value = 1.946416m
                        },
                        new
                        {
                            Id = 2,
                            CurrencyId = 9,
                            Date = "1999-03-03",
                            Value = 1.746727m
                        },
                        new
                        {
                            Id = 3,
                            CurrencyId = 10,
                            Date = "1999-03-03",
                            Value = 1.946416m
                        },
                        new
                        {
                            Id = 4,
                            CurrencyId = 13,
                            Date = "1999-03-03",
                            Value = 2.178089m
                        },
                        new
                        {
                            Id = 5,
                            CurrencyId = 18,
                            Date = "1999-03-03",
                            Value = 1.089045m
                        },
                        new
                        {
                            Id = 6,
                            CurrencyId = 21,
                            Date = "1999-03-03",
                            Value = 2.374996m
                        },
                        new
                        {
                            Id = 7,
                            CurrencyId = 22,
                            Date = "1999-03-03",
                            Value = 2.131304m
                        },
                        new
                        {
                            Id = 8,
                            CurrencyId = 24,
                            Date = "1999-03-03",
                            Value = 1.624130m
                        },
                        new
                        {
                            Id = 9,
                            CurrencyId = 26,
                            Date = "1999-03-03",
                            Value = 1.179559m
                        },
                        new
                        {
                            Id = 10,
                            CurrencyId = 29,
                            Date = "1999-03-03",
                            Value = 1.442242m
                        },
                        new
                        {
                            Id = 11,
                            CurrencyId = 30,
                            Date = "1999-03-03",
                            Value = 2.283165m
                        },
                        new
                        {
                            Id = 12,
                            CurrencyId = 31,
                            Date = "1999-03-03",
                            Value = 1.624130m
                        },
                        new
                        {
                            Id = 13,
                            CurrencyId = 32,
                            Date = "1999-03-03",
                            Value = 2.131304m
                        },
                        new
                        {
                            Id = 14,
                            CurrencyId = 33,
                            Date = "1999-03-03",
                            Value = 1.089045m
                        },
                        new
                        {
                            Id = 15,
                            CurrencyId = 35,
                            Date = "1999-03-03",
                            Value = 1.089045m
                        },
                        new
                        {
                            Id = 16,
                            CurrencyId = 38,
                            Date = "1999-03-03",
                            Value = 1.089045m
                        },
                        new
                        {
                            Id = 17,
                            CurrencyId = 41,
                            Date = "1999-03-03",
                            Value = 1.740280m
                        },
                        new
                        {
                            Id = 18,
                            CurrencyId = 42,
                            Date = "1999-03-03",
                            Value = 1.774681m
                        },
                        new
                        {
                            Id = 19,
                            CurrencyId = 44,
                            Date = "1999-03-03",
                            Value = 2.283165m
                        },
                        new
                        {
                            Id = 20,
                            CurrencyId = 46,
                            Date = "1999-03-03",
                            Value = 2.178089m
                        },
                        new
                        {
                            Id = 21,
                            CurrencyId = 47,
                            Date = "1999-03-03",
                            Value = 1.774681m
                        },
                        new
                        {
                            Id = 22,
                            CurrencyId = 48,
                            Date = "1999-03-03",
                            Value = 2.131304m
                        },
                        new
                        {
                            Id = 23,
                            CurrencyId = 50,
                            Date = "1999-03-03",
                            Value = 2.178089m
                        },
                        new
                        {
                            Id = 24,
                            CurrencyId = 51,
                            Date = "1999-03-03",
                            Value = 2.283165m
                        },
                        new
                        {
                            Id = 25,
                            CurrencyId = 53,
                            Date = "1999-03-03",
                            Value = 1.774681m
                        },
                        new
                        {
                            Id = 26,
                            CurrencyId = 54,
                            Date = "1999-03-03",
                            Value = 1.089045m
                        },
                        new
                        {
                            Id = 27,
                            CurrencyId = 55,
                            Date = "1999-03-03",
                            Value = 2.374996m
                        },
                        new
                        {
                            Id = 28,
                            CurrencyId = 56,
                            Date = "1999-03-03",
                            Value = 2.178089m
                        },
                        new
                        {
                            Id = 29,
                            CurrencyId = 58,
                            Date = "1999-03-03",
                            Value = 1.946416m
                        },
                        new
                        {
                            Id = 30,
                            CurrencyId = 59,
                            Date = "1999-03-03",
                            Value = 1.946416m
                        },
                        new
                        {
                            Id = 31,
                            CurrencyId = 61,
                            Date = "1999-03-03",
                            Value = 2.178089m
                        },
                        new
                        {
                            Id = 32,
                            CurrencyId = 63,
                            Date = "1999-03-03",
                            Value = 2.178089m
                        },
                        new
                        {
                            Id = 33,
                            CurrencyId = 64,
                            Date = "1999-03-03",
                            Value = 2.131304m
                        },
                        new
                        {
                            Id = 34,
                            CurrencyId = 65,
                            Date = "1999-03-03",
                            Value = 2.374996m
                        },
                        new
                        {
                            Id = 35,
                            CurrencyId = 66,
                            Date = "1999-03-03",
                            Value = 1.946416m
                        },
                        new
                        {
                            Id = 36,
                            CurrencyId = 68,
                            Date = "1999-03-03",
                            Value = 2.283165m
                        },
                        new
                        {
                            Id = 37,
                            CurrencyId = 70,
                            Date = "1999-03-03",
                            Value = 1.624130m
                        },
                        new
                        {
                            Id = 38,
                            CurrencyId = 71,
                            Date = "1999-03-03",
                            Value = 2.374996m
                        },
                        new
                        {
                            Id = 39,
                            CurrencyId = 72,
                            Date = "1999-03-03",
                            Value = 2.178089m
                        },
                        new
                        {
                            Id = 40,
                            CurrencyId = 73,
                            Date = "1999-03-03",
                            Value = 2.178089m
                        },
                        new
                        {
                            Id = 41,
                            CurrencyId = 74,
                            Date = "1999-03-03",
                            Value = 1.624130m
                        },
                        new
                        {
                            Id = 42,
                            CurrencyId = 75,
                            Date = "1999-03-03",
                            Value = 1.946416m
                        },
                        new
                        {
                            Id = 43,
                            CurrencyId = 76,
                            Date = "1999-03-03",
                            Value = 2.374996m
                        },
                        new
                        {
                            Id = 44,
                            CurrencyId = 78,
                            Date = "1999-03-03",
                            Value = 2.178089m
                        },
                        new
                        {
                            Id = 45,
                            CurrencyId = 79,
                            Date = "1999-03-03",
                            Value = 2.178089m
                        },
                        new
                        {
                            Id = 46,
                            CurrencyId = 80,
                            Date = "1999-03-03",
                            Value = 1.946416m
                        },
                        new
                        {
                            Id = 47,
                            CurrencyId = 81,
                            Date = "1999-03-03",
                            Value = 2.178089m
                        },
                        new
                        {
                            Id = 48,
                            CurrencyId = 82,
                            Date = "1999-03-03",
                            Value = 2.178089m
                        },
                        new
                        {
                            Id = 49,
                            CurrencyId = 84,
                            Date = "1999-03-03",
                            Value = 2.283165m
                        },
                        new
                        {
                            Id = 50,
                            CurrencyId = 86,
                            Date = "1999-03-03",
                            Value = 2.178089m
                        });
                });

            modelBuilder.Entity("ExchangeRateAPI.Model.UpdateLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ApiCallSuccess")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DbUpdateDate")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("UpdateLogs");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ApiCallSuccess = "NA",
                            DbUpdateDate = "14.08.2023 12:15:49",
                            Message = "DB Created"
                        });
                });

            modelBuilder.Entity("ExchangeRateAPI.Model.Rate", b =>
                {
                    b.HasOne("ExchangeRateAPI.Model.Currency", "Currency")
                        .WithMany("Rates")
                        .HasForeignKey("CurrencyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Currency");
                });

            modelBuilder.Entity("ExchangeRateAPI.Model.Currency", b =>
                {
                    b.Navigation("Rates");
                });
#pragma warning restore 612, 618
        }
    }
}
